const { Client, GatewayIntentBits, EmbedBuilder, PermissionFlagsBits, ActionRowBuilder, StringSelectMenuBuilder, ChannelType } = require("discord.js");
const fs = require("fs");
const http = require("http");

const PREFIX = "b!";
const DATA_FILE = "./welcome-config.json";
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent, GatewayIntentBits.GuildPresences] });

let data = {};
if (fs.existsSync(DATA_FILE)) {
  try { data = JSON.parse(fs.readFileSync(DATA_FILE, "utf8")); } catch { data = {}; }
}
const defaults = () => ({ welcomeChannel: null, autoRole: null, logsChannel: null, autoReplies: {}, autoReactions: {}, warnings: {}, maintenance: false });
function saveData() { fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2)); }
function getGuildData(id) { if (!data[id]) { data[id] = defaults(); saveData(); } return data[id]; }
function isAdmin(message) { return Boolean(message.member?.permissions.has(PermissionFlagsBits.Administrator)); }
function adminOnly(message) { if (!isAdmin(message)) { message.reply({ content: "🚫 Solo los administradores pueden usar los comandos del bot." }).catch(() => {}); return false; } return true; }
const user = m => m.mentions.members.first();
const role = m => m.mentions.roles.first();
const channel = m => m.mentions.channels.first();
function duration(ms) { const s = Math.floor(ms / 1000); return `${Math.floor(s / 86400)}d ${Math.floor(s % 86400 / 3600)}h ${Math.floor(s % 3600 / 60)}m`; }
async function sendLog(guild, title, description) { const d = getGuildData(guild.id); const c = d.logsChannel && guild.channels.cache.get(d.logsChannel); if (!c) return; await c.send({ embeds: [new EmbedBuilder().setColor(0x3498db).setTitle(`♟️🃏 ${title}`).setDescription(description).setFooter({ text: "♟️ Fusake • 🃏 Redkings" }).setTimestamp()] }).catch(() => {}); }
function welcomeDM() { return { content: `# Bienvenido/a a Redkings\n\n> 🎉 **¡Bienvenido/a a Redkings!** 🃏\n> Nos alegra mucho tenerte aquí. ✨\n\n> 📌 Explora el servidor, conoce a la comunidad y disfruta de todas las funciones que tenemos preparadas para ti.\n> 🤝 Respeta a los demás, sigue las reglas y, sobre todo, ¡diviértete!\n\n> 💎 **¡Tu aventura en Redkings comienza ahora!**\n> Esperamos verte formar parte de nuestra comunidad. 🖤\n\n🔗 **Links de nuestra network:**\nhttps://discord.gg/M8kCgt8JJ\nhttps://discord.gg/DaUJ4a3eg\nhttps://discord.gg/cGc9QQqPnX` }; }

client.once("ready", () => { console.log(`♟️🃏 Fusake conectado como ${client.user.tag}`); console.log(`🌐 Servidores: ${client.guilds.cache.size}`); console.log(`⚡ Prefijo: ${PREFIX}`); client.user.setPresence({ activities: [{ name: "♟️ Ajedrez + 🃏 Póker", type: 0 }], status: "online" }); });

client.on("guildMemberAdd", async member => {
  const d = getGuildData(member.guild.id);
  if (d.welcomeChannel) {
    const c = member.guild.channels.cache.get(d.welcomeChannel);
    if (c) await c.send({ embeds: [new EmbedBuilder().setColor(0xf1c40f).setTitle("♟️🃏 ¡NUEVO JUGADOR EN LA MESA! 🃏♟️").setDescription(`¡Bienvenido ${member} 👋\n\nHas entrado a ―═★❯❯ RƐɗ KɪƝƓS ♦ .! .\n\n♟️ Mueve tus piezas con estrategia.\n🃏 Juega tus cartas con inteligencia.\n\n¡Esperamos que disfrutes de la comunidad! 🎉🎊\n♣️ pásate por el canal de <#1533949497812586646> <#1516922343195148520> <#1523782602379624662> para saber más de ti!!!!\n\n♟️ Tu próximo movimiento puede cambiar la partida 🃏`).setThumbnail(member.user.displayAvatarURL()).setFooter({ text: "♟️ Tu próximo movimiento puede cambiar la partida 🃏" }).setTimestamp()], allowedMentions: { users: [member.id] } }).catch(() => {});
  }
  if (d.autoRole) { const r = member.guild.roles.cache.get(d.autoRole); if (r?.editable) await member.roles.add(r).catch(() => {}); }
  try { await member.send(welcomeDM()); } catch { console.log(`⚠️ No se pudo enviar el MD a ${member.user.tag}`); }
});

const help = {
  moderacion: ["♟️🛡️ MODERACIÓN 🛡️♟️", "b!ban @usuario [razón]", "b!unban ID", "b!kick @usuario [razón]", "b!timeout @usuario minutos", "b!untimeout @usuario", "b!warn @usuario [razón]", "b!warnings @usuario", "b!clearwarnings @usuario", "b!purge cantidad", "b!clear cantidad", "b!slowmode segundos", "b!lock", "b!unlock", "b!lockall", "b!unlockall", "b!nick @usuario nombre", "b!softban @usuario [razón]", "b!dehoist", "b!roleall @rol", "b!removeroleall @rol", "b!checkmember @usuario"],
  configuracion: ["♟️⚙️ CONFIGURACIÓN ⚙️🃏", "b!bienvenida #canal", "b!bienvenida off", "b!autoroles @rol", "b!autorespuestas palabra respuesta", "b!autoreacciones palabra emoji", "b!delreply palabra", "b!delreaction palabra", "b!logs #canal", "b!setlog #canal", "b!maintenance", "b!config", "b!resetconfig", "b!setautorole @rol", "b!clearautorole", "b!clearlogs", "b!maintenanceon", "b!maintenanceoff"],
  servidor: ["♟️🏠 SERVIDOR 🏠🃏", "b!serverinfo", "b!userinfo @usuario", "b!roleinfo @rol", "b!channelinfo #canal", "b!roles", "b!members", "b!membercount", "b!bots", "b!humans", "b!emojis", "b!boosts", "b!staff", "b!permissions @usuario", "b!avatar @usuario", "b!servericon", "b!serverbanner", "b!created", "b!channelcount", "b!categorycount", "b!rolecount", "b!memberlist"],
  staff: ["🃏🧰 HERRAMIENTAS DE STAFF 🧰♟️", "b!say mensaje", "b!announce mensaje", "b!embed mensaje", "b!poll pregunta", "b!move @usuario #voz", "b!disconnect @usuario", "b!role add @usuario @rol", "b!role remove @usuario @rol", "b!addrole @usuario @rol", "b!removerole @usuario @rol", "b!setstatus texto", "b!clearchannel [cantidad]", "b!renamechannel nombre", "b!dm @usuario mensaje", "b!react emoji", "b!clearlast"],
  bot: ["♟️🤖 BOT 🤖🃏", "b!help", "b!ayuda", "b!ping", "b!uptime", "b!botinfo", "b!botavatar URL", "b!botname nombre", "b!restart", "b!serverlist", "b!memory", "b!config"]
};
function helpMenu() { return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId("fusake_help").setPlaceholder("♟️🃏 Selecciona una categoría").addOptions(Object.entries(help).map(([value, v]) => ({ value, label: value[0].toUpperCase() + value.slice(1), description: "Comandos de " + value, emoji: value === "moderacion" ? "♟️" : value === "configuracion" ? "⚙️" : value === "servidor" ? "🏠" : value === "staff" ? "🃏" : "🤖" })))); }

client.on("messageCreate", async message => {
  if (message.author.bot || !message.guild) return;
  const d = getGuildData(message.guild.id), lower = message.content.toLowerCase();
  if (d.autoReplies?.[lower]) await message.channel.send({ content: d.autoReplies[lower], allowedMentions: { parse: [] } }).catch(() => {});
  if (d.autoReactions?.[lower]) await message.react(d.autoReactions[lower]).catch(() => {});
  if (!message.content.startsWith(PREFIX)) return;
  const args = message.content.slice(PREFIX.length).trim().split(/\s+/), cmd = args.shift()?.toLowerCase();
  if (!cmd || !adminOnly(message)) return;
  const reply = x => message.reply(x);
  if (cmd === "help" || cmd === "ayuda") return reply({ embeds: [new EmbedBuilder().setColor(0xf1c40f).setTitle("♟️🃏 PANEL DE FUSAKE 🃏♟️").setDescription(`╔══════════════════════╗\n   ♟️ **AJEDREZ + PÓKER** 🃏\n╚══════════════════════╝\n\n**Prefijo:** \`${PREFIX}\`\n\n👑 **Acceso exclusivo para administradores**\n\n♟️ Mueve tus piezas.\n🃏 Juega tus cartas.\n\nSelecciona una categoría para ver los comandos.`).setFooter({ text: "♟️🃏 Fusake • La partida continúa..." })], components: [helpMenu()] });
  if (cmd === "bienvenida") { if (args[0]?.toLowerCase() === "off") { d.welcomeChannel = null; saveData(); return reply("♟️🃏 Bienvenidas desactivadas."); } const c = channel(message); if (!c) return reply(`Usa **${PREFIX}bienvenida #canal** o **${PREFIX}bienvenida off**`); d.welcomeChannel = c.id; saveData(); return reply(`♟️🃏 Las nuevas bienvenidas aparecerán en ${c}.`); }
  if (["autoroles", "setautorole"].includes(cmd)) { if (args[0]?.toLowerCase() === "off") d.autoRole = null; else { const r = role(message); if (!r) return reply("❌ Usa **b!autoroles @rol**"); d.autoRole = r.id; } saveData(); return reply("🎭 Auto rol actualizado."); }
  if (["clearautorole"].includes(cmd)) { d.autoRole = null; saveData(); return reply("🃏 Auto rol eliminado correctamente."); }
  if (["logs", "setlog"].includes(cmd)) { if (args[0]?.toLowerCase() === "off") d.logsChannel = null; else { const c = channel(message); if (!c) return reply("❌ Usa **b!logs #canal**"); d.logsChannel = c.id; } saveData(); return reply("📋 Canal de logs actualizado."); }
  if (cmd === "clearlogs") { d.logsChannel = null; saveData(); return reply("♟️ Canal de logs eliminado."); }
  if (cmd === "maintenance" || cmd === "maintenanceon" || cmd === "maintenanceoff") { d.maintenance = cmd === "maintenance" ? !d.maintenance : cmd === "maintenanceon"; saveData(); return reply(`🔧 Modo mantenimiento **${d.maintenance ? "ACTIVADO" : "DESACTIVADO"}**.`); }
  if (cmd === "config") return reply({ embeds: [new EmbedBuilder().setColor(0x3498db).setTitle("♟️🃏 Configuración de Fusake").addFields({ name: "👋 Bienvenida", value: d.welcomeChannel ? `<#${d.welcomeChannel}>` : "Desactivado", inline: true }, { name: "🎭 Auto rol", value: d.autoRole ? `<@&${d.autoRole}>` : "Desactivado", inline: true }, { name: "📋 Logs", value: d.logsChannel ? `<#${d.logsChannel}>` : "Desactivados", inline: true }, { name: "🔧 Mantenimiento", value: d.maintenance ? "Activado" : "Desactivado", inline: true })] });
  if (cmd === "resetconfig") { data[message.guild.id] = defaults(); saveData(); return reply("♻️ Configuración reiniciada."); }
  if (["autorespuestas", "autoreacciones"].includes(cmd)) { const key = cmd === "autorespuestas" ? "autoReplies" : "autoReactions", trigger = args.shift()?.toLowerCase(), value = args.join(" "); if (!trigger || !value) return reply(`❌ Usa **b!${cmd} palabra ${cmd === "autorespuestas" ? "respuesta" : "emoji"}**`); d[key][trigger] = value; saveData(); return reply("🤖 Configuración guardada."); }
  if (cmd === "delreply" || cmd === "delreaction") { const key = cmd === "delreply" ? "autoReplies" : "autoReactions"; delete d[key][args[0]?.toLowerCase()]; saveData(); return reply("🗑️ Configuración eliminada."); }
  if (["ban", "kick"].includes(cmd)) { const m = user(message); if (!m) return reply(`❌ Usa **b!${cmd} @usuario [razón]**`); const reason = args.slice(1).join(" ") || "Sin razón especificada"; if (cmd === "ban") await m.ban({ reason }).catch(() => {}); else await m.kick(reason).catch(() => {}); await reply(`${cmd === "ban" ? "♟️ Usuario baneado" : "♟️ Usuario expulsado"}: **${m.user.tag}**\n📝 **Razón:** ${reason}`); return sendLog(message.guild, cmd, `**Usuario:** ${m.user.tag}\n**Por:** ${message.author.tag}\n**Razón:** ${reason}`); }
  if (cmd === "softban") { const m = user(message); if (!m) return reply("❌ Usa **b!softban @usuario [razón]**"); const reason = args.slice(1).join(" ") || "Sin razón especificada"; await m.ban({ reason, deleteMessageSeconds: 86400 }).catch(() => {}); await message.guild.members.unban(m.id).catch(() => {}); return reply(`♟️🃏 **Softban aplicado a ${m.user.tag}.**`); }
  if (["timeout", "untimeout"].includes(cmd)) { const m = user(message); if (!m) return reply("❌ Debes mencionar un usuario."); const min = Number(args[1]); await m.timeout(cmd === "untimeout" ? null : min * 60000, "Moderación administrativa").catch(() => {}); return reply(cmd === "untimeout" ? `🃏 Timeout retirado a **${m.user.tag}**.` : `⏳ **${m.user.tag}** recibió timeout de **${min} minutos**.`); }
  if (["warn", "warnings", "clearwarnings"].includes(cmd)) { const m = user(message); if (!m) return reply("❌ Debes mencionar un usuario."); if (cmd === "warn") { d.warnings[m.id] ??= []; d.warnings[m.id].push({ reason: args.slice(1).join(" ") || "Sin razón especificada", moderator: message.author.tag, date: new Date().toISOString() }); saveData(); return reply(`⚠️ **${m.user.tag}** recibió una advertencia.`); } if (cmd === "clearwarnings") { delete d.warnings[m.id]; saveData(); return reply(`🧹 Advertencias eliminadas de **${m.user.tag}**.`); } return reply(d.warnings[m.id]?.map((w, i) => `**${i + 1}.** ${w.reason} — ${w.moderator}`).join("\n") || `✅ **${m.user.tag}** no tiene advertencias.`); }
  if (["purge", "clear", "clearchannel"].includes(cmd)) { const n = Number(args[0]) || (cmd === "clearchannel" ? 50 : 0); if (n < 1 || n > 100) return reply("❌ Usa una cantidad entre **1 y 100**."); const deleted = await message.channel.bulkDelete(n, true).catch(() => null); return deleted ? reply(`♟️🧹 Se limpiaron **${deleted.size} mensajes**.`) : reply("❌ No pude limpiar el canal."); }
  if (["lock", "unlock"].includes(cmd)) { await message.channel.permissionOverwrites.edit(message.guild.roles.everyone, { SendMessages: cmd === "lock" ? false : null }).catch(() => {}); return reply(cmd === "lock" ? "🔒♟️ Canal bloqueado." : "🔓🃏 Canal desbloqueado."); }
  if (["lockall", "unlockall"].includes(cmd)) { let n = 0; for (const c of message.guild.channels.cache.values()) if ([ChannelType.GuildText, ChannelType.GuildAnnouncement].includes(c.type)) { await c.permissionOverwrites.edit(message.guild.roles.everyone, { SendMessages: cmd === "lockall" ? false : null }).catch(() => {}); n++; } return reply(`${cmd === "lockall" ? "🔒♟️" : "🔓🃏"} Se actualizaron **${n} canales**.`); }
  if (cmd === "slowmode") { const n = Number(args[0]); if (Number.isNaN(n) || n < 0 || n > 21600) return reply("❌ Usa un valor entre **0 y 21600 segundos**."); await message.channel.setRateLimitPerUser(n).catch(() => {}); return reply(`🐌 Slowmode establecido en **${n} segundos**.`); }
  if (cmd === "nick" || cmd === "dehoist") { const members = cmd === "nick" ? [user(message)] : [...message.guild.members.cache.filter(m => /^[^a-zA-Z0-9áéíóúÁÉÍÓÚ]/.test(m.displayName)).values()]; if (cmd === "nick" && (!members[0] || !args.slice(1).join(" "))) return reply("❌ Usa **b!nick @usuario nuevo nombre**"); for (const m of members) if (m?.manageable) await m.setNickname(cmd === "nick" ? args.slice(1).join(" ") : m.displayName.replace(/^[^a-zA-Z0-9áéíóúÁÉÍÓÚ]+/, "")).catch(() => {}); return reply("✏️ Nombres actualizados."); }
  if (["roleall", "removeroleall"].includes(cmd)) { const r = role(message); if (!r || r.position >= message.guild.members.me.roles.highest.position) return reply("❌ Rol inválido o superior al mío."); let n = 0; for (const m of message.guild.members.cache.values()) { if (cmd === "roleall" ? !m.roles.cache.has(r.id) && !m.user.bot : m.roles.cache.has(r.id)) { await m.roles[cmd === "roleall" ? "add" : "remove"](r).catch(() => {}); n++; } } return reply(`♟️🃏 Se modificó el rol en **${n} usuarios**.`); }
  if (cmd === "checkmember" || cmd === "userinfo") { const m = user(message) || message.member; return reply({ embeds: [new EmbedBuilder().setColor(0x3498db).setTitle(`♟️🃏 ${m.user.tag}`).setThumbnail(m.user.displayAvatarURL()).addFields({ name: "🆔 ID", value: m.id, inline: true }, { name: "🟢 Estado", value: m.presence?.status || "offline", inline: true }, { name: "🎭 Roles", value: m.roles.cache.filter(r => r.id !== message.guild.id).map(String).join(", ") || "Ninguno" })] }); }
  if (cmd === "serverinfo") return reply({ embeds: [new EmbedBuilder().setColor(0x3498db).setTitle(`♟️🃏 ${message.guild.name}`).setThumbnail(message.guild.iconURL()).setDescription(`👑 Dueño: <@${message.guild.ownerId}>\n👥 Miembros: ${message.guild.memberCount}\n💬 Canales: ${message.guild.channels.cache.size}\n🎭 Roles: ${message.guild.roles.cache.size}\n😀 Emojis: ${message.guild.emojis.cache.size}\n🚀 Boosts: ${message.guild.premiumSubscriptionCount || 0}`)] });
  if (["members", "membercount"].includes(cmd)) return reply(`👥 Miembros: **${message.guild.memberCount}**`);
  if (cmd === "bots" || cmd === "humans") return reply(`${cmd === "bots" ? "🤖 Bots" : "♟️ Jugadores humanos"}: **${message.guild.members.cache.filter(m => cmd === "bots" ? m.user.bot : !m.user.bot).size}**`);
  if (cmd === "emojis" || cmd === "boosts" || cmd === "rolecount" || cmd === "categorycount") return reply(`🃏 Resultado: **${cmd === "emojis" ? message.guild.emojis.cache.size : cmd === "boosts" ? message.guild.premiumSubscriptionCount || 0 : cmd === "rolecount" ? message.guild.roles.cache.size - 1 : message.guild.channels.cache.filter(c => c.type === ChannelType.GuildCategory).size}**`);
  if (cmd === "channelcount") return reply(`♟️ Texto: **${message.guild.channels.cache.filter(c => c.type === ChannelType.GuildText).size}**\n🃏 Voz: **${message.guild.channels.cache.filter(c => c.type === ChannelType.GuildVoice).size}**`);
  if (cmd === "memberlist") return reply({ embeds: [new EmbedBuilder().setTitle("♟️🃏 Jugadores de la mesa").setDescription(message.guild.members.cache.filter(m => !m.user.bot).first(30).map(m => `♟️ ${m}`).join("\n") || "No hay miembros disponibles.")] });
  if (cmd === "roles") return reply(message.guild.roles.cache.filter(r => r.id !== message.guild.id).map(r => r.toString()).join("\n") || "No hay roles.");
  if (cmd === "roleinfo") { const r = role(message); return r ? reply(`🃏 **${r.name}**\n🆔 ${r.id}\n👥 ${r.members.size} miembros\n📌 Posición ${r.position}`) : reply("❌ Usa **b!roleinfo @rol**"); }
  if (cmd === "channelinfo") { const c = channel(message) || message.channel; return reply(`💬 **${c.name}**\n🆔 ${c.id}\n📂 Tipo ${c.type}`); }
  if (["servericon", "serverbanner"].includes(cmd)) { const url = cmd === "servericon" ? message.guild.iconURL({ size: 1024 }) : message.guild.bannerURL({ size: 1024 }); return url ? reply({ embeds: [new EmbedBuilder().setTitle(cmd === "servericon" ? "♟️ Icono del servidor" : "🃏 Banner del servidor").setImage(url)] }) : reply("❌ No disponible."); }
  if (cmd === "staff") return reply(message.guild.members.cache.filter(m => m.permissions.has(PermissionFlagsBits.Administrator)).map(m => `👑 ${m}`).join("\n") || "No se encontraron administradores.");
  if (cmd === "permissions") { const m = user(message) || message.member; return reply(m.permissions.toArray().map(p => `• ${p}`).join("\n") || "Sin permisos."); }
  if (cmd === "avatar") { const m = user(message) || message.member; return reply({ embeds: [new EmbedBuilder().setTitle(`🃏 Avatar de ${m.user.tag}`).setImage(m.user.displayAvatarURL({ size: 1024 }))] }); }
  if (cmd === "created") return reply(`📅 El servidor fue creado <t:${Math.floor(message.guild.createdTimestamp / 1000)}:F>.`);
  if (cmd === "say" || cmd === "announce" || cmd === "embed") { const text = args.join(" "); if (!text) return reply(`❌ Usa **b!${cmd} mensaje**`); if (cmd === "say") { await message.delete().catch(() => {}); return message.channel.send({ content: text, allowedMentions: { parse: [] } }); } return message.channel.send({ embeds: [new EmbedBuilder().setColor(cmd === "announce" ? 0xf1c40f : 0x3498db).setTitle(cmd === "announce" ? "♟️🃏 ANUNCIO" : null).setDescription(text)] }); }
  if (cmd === "poll") { const q = args.join(" "); if (!q) return reply("❌ Usa **b!poll pregunta**"); const p = await message.channel.send({ embeds: [new EmbedBuilder().setTitle("♟️🃏 Encuesta").setDescription(q).setFooter({ text: "👍 Sí • 👎 No" })] }); await p.react("👍").catch(() => {}); await p.react("👎").catch(() => {}); return; }
  if (["move", "disconnect"].includes(cmd)) { const m = user(message); if (!m) return reply("❌ Debes mencionar un usuario."); if (cmd === "move") { const c = channel(message); if (!c || c.type !== ChannelType.GuildVoice) return reply("❌ Menciona un canal de voz."); await m.voice.setChannel(c).catch(() => {}); return reply(`🔊 **${m.user.tag}** fue movido a ${c}.`); } await m.voice.disconnect().catch(() => {}); return reply(`🔇 **${m.user.tag}** fue desconectado.`); }
  if (cmd === "setstatus") { const text = args.join(" "); if (!text) return reply("❌ Usa **b!setstatus texto**"); client.user.setPresence({ activities: [{ name: text, type: 0 }], status: "online" }); return reply(`🤖 Estado cambiado a **${text}**.`); }
  if (["addrole", "removerole", "role"].includes(cmd)) { const action = cmd === "role" ? args.shift()?.toLowerCase() : cmd === "addrole" ? "add" : "remove", m = user(message), r = role(message); if (!m || !r || !["add", "remove"].includes(action)) return reply("❌ Usa **b!role add @usuario @rol**"); await m.roles[action](r).catch(() => {}); return reply(`🎭 Rol ${r} actualizado para **${m.user.tag}**.`); }
  if (cmd === "renamechannel") { const name = args.join("-").toLowerCase(); if (!name) return reply("❌ Usa **b!renamechannel nuevo-nombre**"); await message.channel.setName(name).catch(() => {}); return reply(`🃏 Canal renombrado a **${name}**.`); }
  if (cmd === "dm") { const m = user(message), text = args.slice(1).join(" "); if (!m || !text) return reply("❌ Usa **b!dm @usuario mensaje**"); try { await m.send({ content: text, allowedMentions: { parse: [] } }); return reply("💌 Mensaje enviado."); } catch { return reply("❌ No pude enviar el MD."); } }
  if (cmd === "react") { if (!args[0]) return reply("❌ Usa **b!react emoji**"); await message.react(args[0]).catch(() => {}); return reply("🃏 Reacción añadida."); }
  if (cmd === "clearlast") { const ms = await message.channel.messages.fetch({ limit: 10 }).catch(() => null); if (!ms) return reply("❌ No pude obtener los mensajes."); const bots = ms.filter(m => m.author.id === client.user.id); for (const m of bots.values()) await m.delete().catch(() => {}); return reply(`♟️ Eliminé **${bots.size} mensajes recientes de Fusake**.`); }
  if (cmd === "botavatar") { try { await client.user.setAvatar(args[0]); return reply("♟️🃏 Avatar de Fusake actualizado."); } catch { return reply("❌ No pude cambiar el avatar."); } }
  if (cmd === "botname") { try { await client.user.setUsername(args.join(" ")); return reply("🃏 Nombre del bot cambiado."); } catch { return reply("❌ No pude cambiar el nombre."); } }
  if (cmd === "restart") { await reply("♟️ Fusake se está reiniciando..."); setTimeout(() => process.exit(0), 1500); return; }
  if (cmd === "serverlist") return reply(client.guilds.cache.map(g => `♟️ **${g.name}** — ${g.memberCount} miembros`).join("\n"));
  if (cmd === "memory") { const m = process.memoryUsage(); return reply(`🧠 RAM utilizada: **${Math.round(m.heapUsed / 1024 / 1024)} MB**\n📦 Heap total: **${Math.round(m.heapTotal / 1024 / 1024)} MB**`); }
  if (cmd === "botinfo") return reply(`♟️🃏 **${client.user.tag}**\n🌐 Servidores: ${client.guilds.cache.size}\n📡 Ping: ${client.ws.ping}ms\n⚡ Prefijo: ${PREFIX}`);
  if (cmd === "uptime") return reply(`⏱️ Fusake lleva encendido **${duration(client.uptime)}**.`);
  if (cmd === "ping") return reply(`🏓 Pong! **${client.ws.ping}ms**`);
  return reply(`❓ Comando desconocido. Usa **${PREFIX}help** para ver el menú.`);
});

client.on("interactionCreate", async interaction => { if (!interaction.isStringSelectMenu() || interaction.customId !== "fusake_help") return; if (!interaction.member?.permissions.has(PermissionFlagsBits.Administrator)) return interaction.reply({ content: "🚫 Solo los administradores pueden usar este menú.", ephemeral: true }); const selected = help[interaction.values[0]]; if (!selected) return interaction.reply({ content: "❌ Categoría no encontrada.", ephemeral: true }); return interaction.reply({ embeds: [new EmbedBuilder().setColor(0xf1c40f).setTitle(selected[0]).setDescription(selected.slice(1).map(x => `**${x}**`).join("\n")).setFooter({ text: "♟️🃏 Fusake • Solo administradores" }).setTimestamp()], ephemeral: true }); });

const PORT = process.env.PORT || 3000;
http.createServer((req, res) => { res.writeHead(200, { "Content-Type": "text/plain" }); res.end("♟️🃏 Fusake online"); }).listen(PORT, () => console.log(`🌐 Servidor web activo en el puerto ${PORT}`));
const TOKEN = process.env.DISCORD_TOKEN;
if (!TOKEN) { console.error("❌ Falta la variable DISCORD_TOKEN."); process.exit(1); }
client.login(TOKEN);
